[package]
name = "arson"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.18.1"
serde_json = { version = "1.0.108", features = ["preserve_order"] }
open = "5.0.0"
